spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 146099927945-m5t9i1473otneq4sm7j16ngjkkiuh3vh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

my:
  fileDir: C:/Users/file/