spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metadb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100